create table if not exists public.tactic_rush_players (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (
    char_length(display_name) between 2 and 20
    and display_name = btrim(display_name)
  ),
  updated_at timestamptz not null default now()
);

create table if not exists public.tactic_rush_scores (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  mode text not null check (mode in ('survival', 'threeMinutes', 'fiveMinutes')),
  score integer not null check (score between 0 and 900),
  played_at timestamptz not null default now()
);

create index if not exists tactic_rush_scores_period_idx
  on public.tactic_rush_scores (mode, played_at desc, score desc);

create index if not exists tactic_rush_scores_user_idx
  on public.tactic_rush_scores (user_id, played_at desc);

alter table public.tactic_rush_players enable row level security;
alter table public.tactic_rush_scores enable row level security;

revoke all on public.tactic_rush_players from anon, authenticated;
revoke all on public.tactic_rush_scores from anon, authenticated;

create or replace function public.tactic_rush_set_name(p_display_name text)
returns text
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
  v_name text := regexp_replace(btrim(p_display_name), '\s+', ' ', 'g');
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if char_length(v_name) not between 2 and 20 then
    raise exception 'Display name must contain 2 to 20 characters';
  end if;

  insert into public.tactic_rush_players (user_id, display_name)
  values (v_user_id, v_name)
  on conflict (user_id) do update
    set display_name = excluded.display_name,
        updated_at = now();

  return v_name;
end;
$$;

create or replace function public.tactic_rush_submit_score(
  p_mode text,
  p_score integer
)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if v_user_id is null then
    raise exception 'Authentication required';
  end if;
  if p_mode not in ('survival', 'threeMinutes', 'fiveMinutes') then
    raise exception 'Invalid game mode';
  end if;
  if p_score not between 0 and 900 then
    raise exception 'Invalid score';
  end if;

  insert into public.tactic_rush_players (user_id, display_name)
  values (v_user_id, 'Player-' || upper(substr(v_user_id::text, 1, 4)))
  on conflict (user_id) do nothing;

  insert into public.tactic_rush_scores (user_id, mode, score)
  values (v_user_id, p_mode, p_score);
end;
$$;

create or replace function public.tactic_rush_leaderboard(
  p_mode text,
  p_period text
)
returns table (
  rank bigint,
  display_name text,
  score integer,
  is_me boolean
)
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  with period_start as (
    select case p_period
      when 'daily' then date_trunc('day', now())
      when 'weekly' then date_trunc('week', now())
      when 'monthly' then date_trunc('month', now())
      else null
    end as value
  ),
  best as (
    select
      scores.user_id,
      max(scores.score)::integer as score,
      min(scores.played_at) filter (
        where scores.score = (
          select max(candidate.score)
          from public.tactic_rush_scores candidate
          where candidate.user_id = scores.user_id
            and candidate.mode = scores.mode
            and candidate.played_at >= period_start.value
        )
      ) as achieved_at
    from public.tactic_rush_scores scores
    cross join period_start
    where scores.mode = p_mode
      and period_start.value is not null
      and scores.played_at >= period_start.value
    group by scores.user_id
  ),
  ranked as (
    select
      dense_rank() over (order by best.score desc, best.achieved_at asc) as rank,
      best.user_id,
      best.score
    from best
  )
  select
    ranked.rank,
    players.display_name,
    ranked.score,
    ranked.user_id = auth.uid() as is_me
  from ranked
  join public.tactic_rush_players players on players.user_id = ranked.user_id
  order by ranked.rank, players.display_name
  limit 100;
$$;

revoke all on function public.tactic_rush_set_name(text) from public;
revoke all on function public.tactic_rush_submit_score(text, integer) from public;
revoke all on function public.tactic_rush_leaderboard(text, text) from public;

grant execute on function public.tactic_rush_set_name(text) to authenticated;
grant execute on function public.tactic_rush_submit_score(text, integer) to authenticated;
grant execute on function public.tactic_rush_leaderboard(text, text) to authenticated;
